# Load the data generated by 01GenerateData.R
plot.data <- read.csv("Levy2014Sums200.csv", header=TRUE, stringsAsFactors=FALSE)

max <- max(plot.data) # Max value in the data, used for scaling
plottingHeight <- 1000 # Arbitrary number that provides the graph's height
scaleFactor <- 400 # Discovered through trial and error to keep the graph in the boundaries
gap <- plottingHeight / length(plot.data) # Space between lines

# Used for splines since sometimes they can return negative values
zeroNegatives <- function(x) {
  if (x < 0) { 
    return (0) 
  } else { 
    return (x) 
  }
}


# Create a blank plot
plot(0, 0, xlim=c(0, length(spline(1:length(yVals), yVals)$y)), ylim=c(0,1100), type="n", las=1, xlab=NA, ylab=NA, bty="n", axes=FALSE)

for (i in 1:length(plot.data)) {  
  # Grabs a row of data
  yVals <- as.vector(plot.data[[i]] / max * scaleFactor)
  
  yValsSmoothed <- spline(1:length(yVals), yVals)$y
  yValsSmoothed <- sapply(yValsSmoothed, zeroNegatives)
  
  xValsSmoothed <- c(0, 0:(length(yValsSmoothed) - 1), length(yValsSmoothed))
  yValsSmoothed <- c(plottingHeight, yValsSmoothed + plottingHeight, plottingHeight)
  
  polygon(x = xValsSmoothed, y = yValsSmoothed, border = NA, col = "#ffffff")
  lines(x = xValsSmoothed, y = yValsSmoothed, col="#707070", lwd=1.5)
  
  plottingHeight <- plottingHeight - gap
}

