# Load the data generated by 01GenerateData.R
plot.data <- read.csv("GeneratedData/WorldPopulation.csv", header=TRUE, stringsAsFactors=FALSE)

# Add padding above/below where there was data

# On top
top.padding <- 1:13
for (i in top.padding) {
  plot.data <- cbind(0, plot.data)
}
# On bottom
bottom.padding <- 1:13
for (i in bottom.padding) {
  plot.data <- cbind(plot.data, 0)
}

max <- max(plot.data) # Max value in the data, used for scaling
plottingHeight <- 1000 # Arbitrary number that provides the graph's height
scaleFactor <- 225 # Discovered through trial and error to keep the graph in the boundaries
gap <- plottingHeight / length(plot.data) # Space between lines

# Used for splines since sometimes they can return negative values
zeroNegatives <- function(x) {
  if (x < 0) { 
    return (0) 
  } else { 
    return (x) 
  }
}


# Create a blank plot
yVals <- as.vector(plot.data[[1]] / max * scaleFactor)
plot(0, 0, xlim=c(0, length(spline(1:length(yVals), yVals)$y)), ylim=c(0,1100), type="n", las=1, xlab=NA, ylab=NA, bty="n", axes=FALSE)

for (i in 1:length(plot.data)) {  
  # Grabs a row of data
  yVals <- as.vector(plot.data[[i]] / max * scaleFactor)
  
  yValsSmoothed <- spline(1:length(yVals), yVals)$y
  yValsSmoothed <- sapply(yValsSmoothed, zeroNegatives)
  
  xValsSmoothed <- c(0, 0:(length(yValsSmoothed) - 1), length(yValsSmoothed))
  yValsSmoothed <- c(plottingHeight, yValsSmoothed + plottingHeight, plottingHeight)
  
  polygon(x = xValsSmoothed, y = yValsSmoothed, border = NA, col = "#ffffff")
  lines(x = xValsSmoothed, y = yValsSmoothed, col="#cccccc", lwd=1.5)

  # Plot the peaks with a darker line
  j <- 2 # Skip padding
  while (j <= (length(yValsSmoothed) - 2)) {

    if ((yValsSmoothed[j] - plottingHeight) > 0.05 | (yValsSmoothed[j+1] - plottingHeight) > 0.05) {
        segments(xValsSmoothed[j], yValsSmoothed[j], xValsSmoothed[j+1], yValsSmoothed[j+1], col="#000000", lwd=1.5)
    } else { } # Do nothing 

    j <- j + 1
    
  }
  
  plottingHeight <- plottingHeight - gap
}

