# Load the data generated by 01GenerateData.R
plot.data <- read.csv("GeneratedData/VoteDensity01.csv", header=TRUE, stringsAsFactors=FALSE)

# Add padding above/below where there was data

# On top
top.padding <- 1:23
for (i in top.padding) {
  plot.data <- cbind(0, plot.data)
}
# On bottom
bottom.padding <- 1:23
for (i in bottom.padding) {
  plot.data <- cbind(plot.data, 0)
}

# On left
zero.row <- vector(mode="integer", length=dim(plot.data)[1])

left.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(zero.row, plot.data)
}

# On right
right.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(plot.data, zero.row)
}


max <- max(plot.data) # Max value in the data, used for scaling
plottingHeight <- 1000 # Arbitrary number that provides the graph's height
scaleFactor <- 300 # Discovered through trial and error to keep the graph in the boundaries
gap <- plottingHeight / length(plot.data) # Space between lines

# Used for splines since sometimes they can return negative values
zeroNegatives <- function(x) {
  if (x < 0) { 
    return (0) 
  } else { 
    return (x) 
  }
}

setEPS()
postscript(file = "./Export/VoteDensity01", pointsize=5, width=200, height=200)

# Create a blank plot
yVals <- as.vector(plot.data[[1]] / max * scaleFactor)
plot(0, 0, xlim=c(0, length(spline(1:length(yVals), yVals)$y)), ylim=c(0,1100), type="n", las=1, xlab=NA, ylab=NA, bty="n", axes=FALSE)

plotting.threshold <- 0.2

for (i in 1:length(plot.data)) {  
  # Grabs a row of data
  yVals <- as.vector(plot.data[[i]] / max * scaleFactor)
  
  yValsSmoothed <- spline(1:length(yVals), yVals)$y
  yValsSmoothed <- sapply(yValsSmoothed, zeroNegatives)
  
  xValsSmoothed <- c(0, 0:(length(yValsSmoothed) - 1), length(yValsSmoothed))
  yValsSmoothed <- c(plottingHeight, yValsSmoothed + plottingHeight, plottingHeight)
  
  polygon(x = xValsSmoothed, y = yValsSmoothed, border = NA, col = "#000000")
  lines(x = xValsSmoothed, y = yValsSmoothed, col="#cccccc", lwd=1.5)

  # Plot the peaks with a darker line
  j <- 2 # Skip padding
  while (j <= (length(yValsSmoothed) - 2)) {

    if ((yValsSmoothed[j] - plottingHeight) > plotting.threshold | (yValsSmoothed[j+1] - plottingHeight) > plotting.threshold) {
        segments(xValsSmoothed[j], yValsSmoothed[j], xValsSmoothed[j+1], yValsSmoothed[j+1], col="#ffffff", lwd=1.5)
    } else { } # Do nothing

    j <- j + 1

  }
  while (j <= (length(yValsSmoothed) - 2)) {
    
    currentHeight <- yValsSmoothed[j] - plottingHeight
    nextHeight <- yValsSmoothed[j+1] - plottingHeight
    
    if (currentHeight > plotting.threshold | nextHeight > plotting.threshold) {
      
      height <- if (currentHeight > plotting.threshold) currentHeight else nextHeight
      xPoly <- c()
      yPoly <- c()
      
      while (height > plotting.threshold) {
        xPoly <- c(xPoly, xValsSmoothed[j])
        yPoly <- c(yPoly, yValsSmoothed[j])
        
        j <- j + 1
        height <- yValsSmoothed[j] - plottingHeight
      }
      
      xPoly <- c(xPoly, xValsSmoothed[j])
      yPoly <- c(yPoly, yValsSmoothed[j])
      
      polygon(x = xPoly, y = yPoly, border = NA, col = "#FFFFFF")
      lines(x = xPoly, y = yPoly, col="#8E0000", lwd=1.5)
      
      
    } else { 
      j <- j + 1
    } 
    
  }
  
  plottingHeight <- plottingHeight - gap
}

dev.off()
