library(graphics)
library(tcltk)
library(pracma)

# Load the data generated by 01GenerateData.R
plot.data <- read.csv("GeneratedData/VoteDensity1200.csv", header=TRUE, stringsAsFactors=FALSE)

# Add padding above/below where there was data

# On top
top.padding <- 1:5
for (i in top.padding) {
  plot.data <- cbind(0, plot.data)
}
# On bottom
bottom.padding <- 1:1
for (i in bottom.padding) {
  plot.data <- cbind(plot.data, 0)
}

# On left
zero.row <- vector(mode="integer", length=dim(plot.data)[1])

left.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(zero.row, plot.data)
}

# On right
right.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(plot.data, zero.row)
}


max <- max(plot.data) # Max value in the data, used for scaling
plottingHeight <- 1000 # Arbitrary number that provides the graph's height
scaleFactor <- 300 # Discovered through trial and error to keep the graph in the boundaries
gap <- plottingHeight / length(plot.data) # Space between lines

# Output the file to a 36 inch by 24 inch SVG canvas
plot.width = 36
plot.height = 26.5
svg(filename = "./TestPlots/CanadaSGBigCirclesColorOdd.svg", pointsize=12, width=plot.width, height=plot.height)

# Create a blank plot
yVals <- as.vector(plot.data[[1]] / max * scaleFactor)
plot(0, 0, xlim=c(0, length(yVals)), ylim=c(0,1100), type="n", las=1, xlab=NA, ylab=NA, bty="n", axes=FALSE)

plotting.threshold <- 0.1

plot.length = length(plot.data)

# Plot each line
for (i in 1:plot.length) {
  # Grabs a row of data
  yVals <- as.vector(plot.data[[i]] / max * scaleFactor)
  xVals <- seq_along(yVals)
  # yVals.smooth =  savgol(yVals, 3, forder=4)
  
  # polygon(xVals, yVals + plottingHeight, border = NA, col = "#ffffff")
  lines(xVals, yVals + plottingHeight, col=c("red", "blue"), lwd=0.5, type="o", cex=1 )
  
  plottingHeight <- plottingHeight - gap

}

dev.off()